### ISSUE TITLE
Slackroll 'list-transient' does not always notify multiple kernel installations.

### ISSUE THREAD

**Issue by Richard-Cranium** [rg3/slackroll#15]
The basic scenario is...

run 'slackroll kernel-upgrade'  followed by 'slackroll upgrade' for other package upgrades.

Reboot.

run 'slackroll list-transient'.  No mention of multiple kernels present.

**Comment by rg3** [comment]
Note: It's been several years since I stopped using Slackware. I guess I should install it in a virtual machine for cases like this one, and maybe reopen the "maintainer needed" issue.

If I remember correctly, a local package with multiple installed versions is not in a transient state, because as long as one of the versions matches a remote one, it's OK.

When the list of local packages is rebuilt at some point, however, slackroll will warn you if it detects packages with multiple local versions. You may see this message after "Rebuilding local package list..." but not anymore until the local package list is rebuilt again. That's intended behavior, as a one-time warning, and the warning will be gone after you run kernel-clean, which should probably be run after successfully rebooting to the new kernel.

Does the explanation above make sense to you?

**Comment by aclemons** [comment]
I can confirm. You will only see the error once until the package list is changed again.

Ref: https://github.com/rg3/slackroll/blob/fcfd43b2d8c9808b583b0f66a06bef4796d03752/slackroll#L553

**Comment by Richard-Cranium** [comment]
> Note: It's been several years since I stopped using Slackware. I guess I should install it in a virtual machine for cases like this one, and maybe reopen the "maintainer needed" issue.

Indeed, I'm rather happy that you still expend the effort to support this tool despite your having no use for it .  I've mentioned it a few times over in the [https://www.linuxquestions.org/questions/slackware-14/](Linuxquestions Slackware forum) because it's a very nice tool.

> 
> If I remember correctly, a local package with multiple installed versions is not in a transient state, because as long as one of the versions matches a remote one, it's OK.
> 
> When the list of local packages is rebuilt at some point, however, slackroll will warn you if it detects packages with multiple local versions. You may see this message after "Rebuilding local package list..." but not anymore until the local package list is rebuilt again. That's intended behavior, as a one-time warning, and the warning will be gone after you run kernel-clean, which should probably be run after successfully rebooting to the new kernel.
> 
> Does the explanation above make sense to you?

Updating the documentation to say something similar to the above would be the most cost-effective solution to this issue.

**Comment by rg3** [comment]
> Updating the documentation to say something similar to the above would 
> be the most cost-effective solution to this issue.

Fair enough. Given that rebuilding the local packages database is a step that affects many different operations, adding that detail to the individual documentation of the affected operations would be too complicated. I think a brief mention in the program's main webpage or in the FAQ would be good enough.

**Comment by Richard-Cranium** [comment]
I shall assume that someone will do that very thing.  Closing the issue.

**Comment by rg3** [comment]
Lets keep this one open as a reminder that the documentation changes need to be made.
