### ISSUE TITLE
Can't add blacklist entries per repository

### ISSUE THREAD

**Issue by aclemons** [rg3/slackroll#8]
I'm looking for a way to add blacklist entries per repository. 

The concrete problem is I have both of alienBOB's repositories configured with slackroll (restricted_sbrepos and sbrepos) and want to blacklist some packages in sborepos which are also in restricted_sbrepos so I am not prompted to choose each time a package is updated (like vlc and ffmpeg).

Since the package names and paths are exactly the same, the normal blacklist mechanism doesn't work.

A second use case would be only wanting to install a couple of packages from a repo and not wanting to be prompted about new packages every time a package is added. e.g. only wanting to install chromium and palemoon from alienBOB's repo and not caring about anything else in it. One solution would be setting the blacklist for that repo to `^\.\/(?!chromium|palemoon).*$`

I have started working on a solution but would like to confirm the approach before I prepare a PR.

I don't want to break anyone's existing blacklist, so I was thinking of this:

Change `get_blacklist()` to return a dict, keyed by repo id (None or some non-digit value will be the key for the primary mirror) and values which are arrays of regexes. When loading the current array from a file and iterating the entries, if the entry is a string, it applies to all and is added to the array for the primary mirror and any repos. If the entry is itself an array (tuple), the first element is the repo id, the second element is the regex.

So if the persisted current blacklist is:
`[regex1, regex2]`

and I have 1 repo, it becomes:

```
{
  None: [regex1, regex2],
  0: [regex1, regex]
}
```

When persisting, convert back to an array of tuples. When using the blacklist, fetch the dict and key by the repo id (or None for the primary mirror).

When persisting it becomes:
`[[None, regex1], [None, regex2], [0, regex1], [0, regex2]]`

Now adding and removing from the blacklist is somewhat problematic since the operations currently take a list of ids. Changing this to have the first element be the repo id would break the existing behaviour. I was thinking to leave this command which removes the blacklist from main mirror and adding two new commands `repo-blacklist-add` and `repo-blacklist-del` which take the repo id as the first argument following by the list of index values to remove.

The print-blacklist would remain the same, but would iterate all printing each blacklist in a loop (different example than above):

```
# slackroll print-blacklist
Blacklisted expressions:
    0     regex
End of list
Blacklisted expressions for repo 1:
    0     regex1
    1     regex2
End of list
Blacklisted expressions for repo 3:
    0     regexA
    1     regexB
End of list
```

**Comment by rg3** [comment]
I think I get the problem but I'd like a simpler solution. The current approach has an additional issue: when adding or removing third-party repositories, their indexes change, so you'd have to rearrange blacklist items or delete them, or change the way they're numbered.

I was thinking about adding a special syntax to blacklist regular expressions without breaking existing rules. For example, right now the possibilities of a blacklist RE including the @ character are minimal. No common package name or path contains that character. That allows us to handle blacklist REs in the form expression1@expression2 (read it like "at", email style) by detecting if the RE contains the @ character and splitting the RE in two. Everything up to the first @ is matched as it is now, against the package full name. Everything after must also be a valid RE and would be matched against the package URL. If the RE does not contain @, no check is performed against the package URL. Blacklist REs wouldn't be directly associated with a third party repository. The association would be indirect and via the URL instead of an index, so no special care needs to be taken when adding or removing repos.

Blacklist REs would be strings as they are now. I think the only changes needed would be:

1. In add_blacklist_exprs(), you need to check the second RE if it's present to consider the blacklist expression valid.

2. In get_blacklist_re(), you need to return a list of tuples instead of a list of REs, the first item in the tuple as it is now, the second one could be None or a RE if the blacklist expression contains the special character.

3. In extend_remote_list(), you use the results from get_blacklist_re(). If the second item in each tuple is not None, it needs to be checked against the package URL for the package to be really blacklisted (use its .url() method).

Idea: make a simple function to do the split by @ and return a touple, with the second item being None if no @ is present, and reuse it in several places.

What do you think about that approach?

**Comment by aclemons** [comment]
Seems reasonable to me. I've opened an PR for initial review.
